### ISSUE TITLE
spark to greenplum connector issue in yarn mode

### ISSUE THREAD

**Issue by sunnn** [kongyew/greenplum-spark-jdbc#1]
Greenplum version or build
Gp 5.19

OS version and uname -a
Centos 7

autoconf options used ( config.status --config )
Installation information ( pg_config )
components used for connecting
1.greenplum-spark-connector 1.6.1 jar
2.postgresql latets jar
3.spark version 2.2
4.scala version 2.11

Expected behavior
I'm trying to connect greenplum through spark in local and cluster mode
Local mode working fine but cluster mode fails saying incompatible class def found

Actual behavior
Step to reproduce the behavior
 have used below commands while connecting to greenplum in local and cluster mode

val gscWriteOptionMap = Map("url" -> "jdbc:postgresql://gpadmin:5432/foo","user" -> "changeme","password" -> "changeme","dbschema" -> "example_schema","dbtable" -> "tf","server.hostEnv" -> "10.x.x.x")
2.df.write.format("greenplum").options(gscWriteOptionMap).mode(SaveMode.Overwrite).save()
This works fine in local mode
but gives me an error while running it on cluster mode as below
Caused by: java.lang.IncompatibleClassChangeError: org/eclipse/jetty/server/HttpConnectionFactory
at org.eclipse.jetty.server.ServerConnector.(ServerConnector.java:96)
at io.pivotal.greenplum.spark.externaltable.GpfdistService.start(GpfdistService.scala:63)
at io.pivotal.greenplum.spark.externaltable.GpfdistServiceManager$.getService(GpfdistServiceManager.scala:54)
at io.pivotal.greenplum.spark.externaltable.PartitionWriter.gpfdistService$lzycompute(PartitionWriter.scala:23)
at io.pivotal.greenplum.spark.externaltable.PartitionWriter.gpfdistService(PartitionWriter.scala:22)
at io.pivotal.greenplum.spark.externaltable.PartitionWriter$$anonfun$getClosure$1.apply(PartitionWriter.scala:32)
at io.pivotal.greenplum.spark.externaltable.PartitionWriter$$anonfun$getClosure$1.apply(PartitionWriter.scala:31)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:844)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
at org.apache.spark.scheduler.Task.run(Task.scala:108)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
@kongyew

**Comment by sunnn** [comment]
Closed out as issue was with greenplum database firewall
